//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchForProfessions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionPlanTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdmissionPlanTable()
        {
            this.AdmissionPlanQualificationTable = new HashSet<AdmissionPlanQualificationTable>();
        }
    
        public int ID { get; set; }
        public int IDOrganization { get; set; }
        public int IDSpecialization { get; set; }
        public int IDFormOfTraining { get; set; }
        public string PeriodOfStudy { get; set; }
        public int IDEducationLevel { get; set; }
        public int IDFinancialBasisis { get; set; }
        public int AdmissionPlan { get; set; }
        public bool EntranceTest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdmissionPlanQualificationTable> AdmissionPlanQualificationTable { get; set; }
        public virtual EducationLevelTable EducationLevelTable { get; set; }
        public virtual FinancialBasisTable FinancialBasisTable { get; set; }
        public virtual FormOfTrainingTable FormOfTrainingTable { get; set; }
        public virtual OrganizationTable OrganizationTable { get; set; }
        public virtual SpecializationTable SpecializationTable { get; set; }
    }
}
