//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchForProfessions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionPlanQualificationTable
    {
        public int ID { get; set; }
        public int IDAdmissionPlan { get; set; }
        public int IDQualification { get; set; }
    
        public virtual AdmissionPlanTable AdmissionPlanTable { get; set; }
        public virtual QualificationTable QualificationTable { get; set; }
    }
}
